// Auto-generated by Nextgen Export
// Foundations: every brand token in HEX
// Roles: semantic theme variables resolved to HEX from foundations
export const FOUNDATIONS = {
  "midnight-ash": "#090b0f",
  "photon-white": "#f6f5f1",
  "carbon-fiber": "#11161d",
  "tungsten-gray": "#373b40",
  "titanium-mist": "#9b9fa3",
  "inferno-orange": "#ff3600",
  "crimson-alert": "#ce002f",
  "chart-electric-blue": "#0096e5",
  "chart-neon-pink": "#cd3ec6",
  "chart-ultraviolet": "#9754ed",
  "chart-plasma-teal": "#00bdb5"
} as const;

export const ROLES = {
  "background": "#090b0f",
  "foreground": "#f6f5f1",
  "card": "#11161d",
  "card-foreground": "#f6f5f1",
  "popover": "#11161d",
  "popover-foreground": "#f6f5f1",
  "primary": "#ff3600",
  "primary-foreground": "#f6f5f1",
  "secondary": "#ff3600",
  "secondary-foreground": "#f6f5f1",
  "muted": "#373b40",
  "muted-foreground": "#9b9fa3",
  "accent": "#ff3600",
  "accent-foreground": "#f6f5f1",
  "destructive": "#ce002f",
  "destructive-foreground": "#f6f5f1",
  "success": "#ff3600",
  "success-foreground": "#f6f5f1",
  "sidebar": "#11161d",
  "sidebar-foreground": "#f6f5f1",
  "sidebar-primary": "#ff3600",
  "sidebar-primary-foreground": "#f6f5f1",
  "sidebar-accent": "#ff3600",
  "sidebar-accent-foreground": "#f6f5f1",
  "sidebar-border": "#373b40",
  "sidebar-ring": "#ff3600",
  "border": "#373b40",
  "input": "#373b40",
  "input-foreground": "#f6f5f1",
  "ring": "#ff3600",
  "chart1": "#ff3600",
  "chart2": "#0096e5",
  "chart3": "#cd3ec6",
  "chart4": "#9754ed",
  "chart5": "#00bdb5",
  "chartOutline": "#373b40"
} as const;

export const THEME_COLORS = {
  background: ROLES.background ?? "#0b0b0b",
  primary: ROLES.primary ?? "#7c3aed",
  secondary: ROLES.secondary ?? "#1f2937",
  accent: ROLES.accent ?? "#14b8a6",
  foreground: ROLES.foreground ?? "#fafafa"
} as const;

export const SHADER_COLORS = [
  THEME_COLORS.background,
  THEME_COLORS.primary,
  THEME_COLORS.secondary,
  THEME_COLORS.accent,
  THEME_COLORS.foreground
] as const;

export default THEME_COLORS;
