import { rgbToCmykString, hexToRgbString } from "../brands";

export const APPLE_THEME = {
        name: "Apple",
        id: "apple",
        description: "Global technology leader recognized for its elegant minimalism, precision, and innovative product design.",
        brand: {
            main: {
                name: "Apple Blue (Primary)",
                hex: "#0071E3",
                rgb: hexToRgbString("#0071E3"),
                cmyk: rgbToCmykString(hexToRgbString("#0071E3")),
                variableName: "brand-main",
            },
            on: "#FFFFFF",
            secondary: {
                name: "Apple Gray (Secondary)",
                hex: "#86868B",
                rgb: hexToRgbString("#86868B"),
                cmyk: rgbToCmykString(hexToRgbString("#86868B")),
                variableName: "brand-secondary",
            },
        },
        supportPalette: [
            {
                name: "Apple Red (Destructive)",
                hex: "#FF3B30",
                rgb: hexToRgbString("#FF3B30"),
                cmyk: rgbToCmykString(hexToRgbString("#FF3B30")),
                variableName: "semantic-destructive",
            },
            {
                name: "Apple Green (Success)",
                hex: "#34C759",
                rgb: hexToRgbString("#34C759"),
                cmyk: rgbToCmykString(hexToRgbString("#34C759")),
                variableName: "semantic-success",
            },
            {
                name: "Apple Yellow (Warning)",
                hex: "#FFCC00",
                rgb: hexToRgbString("#FFCC00"),
                cmyk: rgbToCmykString(hexToRgbString("#FFCC00")),
                variableName: "semantic-warning",
            },
            {
                name: "Apple Blue (Info)",
                hex: "#007AFF",
                rgb: hexToRgbString("#007AFF"),
                cmyk: rgbToCmykString(hexToRgbString("#007AFF")),
                variableName: "semantic-info",
            },
        ],
        surface: {
            background: "#FFFFFF",
            card: "#FFFFFF",
            popover: "#FFFFFF",
            on: "#1D1D1F",
            muted: "#F5F5F7",
            mutedForeground: "#86868B",
            brandSubtle: "#E5F0FF",
            textMuted: "#6E6E73",
        },
        semantic: {
            destructive: "#FF3B30",
            success: "#34C759",
            warning: "#FFCC00",
            info: "#007AFF",
        },
        shape: {
            radiusXs: "2px",
            radiusSm: "4px",
            radius: "8px",
            radiusLg: "12px",
            radiusXl: "16px",
            radiusFull: "9999px",
        },
        typography: {
            fontDisplay: "'SF Pro Display', 'Helvetica Neue', sans-serif",
            fontSans: "'SF Pro Text', 'Helvetica Neue', sans-serif",
            fontMono: "'SF Mono', 'Menlo', monospace",
            weightNormal: "400",
            weightMedium: "500",
            weightSemibold: "600",
            weightBold: "700",
            leading: "1.4",
            tracking: "-0.01em",
            fontSizeXs: "0.75rem",
            fontSizeSm: "0.875rem",
            fontSizeBase: "1rem",
            fontSizeLg: "1.25rem",
            fontSizeXl: "1.5rem",
        },
        motion: {
            motionFast: "120ms",
            motionStandard: "250ms",
            motionSlow: "400ms",
            ease: "cubic-bezier(0.25, 0.1, 0.25, 1)",
            easeIn: "cubic-bezier(0.4, 0, 1, 1)",
            easeOut: "cubic-bezier(0, 0, 0.2, 1)",
        },
        elevation: {
            shadowXs: "0 1px 2px rgba(0,0,0,0.05)",
            shadowSm: "0 2px 4px rgba(0,0,0,0.07)",
            shadowMd: "0 4px 8px rgba(0,0,0,0.08)",
            shadowLg: "0 8px 16px rgba(0,0,0,0.1)",
            shadowXl: "0 16px 32px rgba(0,0,0,0.12)",
        },
        spacing: {
            space1: "0.25rem",
            space2: "0.5rem",
            space3: "0.75rem",
            space4: "1rem",
            space5: "1.5rem",
            space6: "2rem",
            space8: "3rem",
            space12: "4rem",
            paddingInput: "0.75rem 1rem",
            paddingButton: "0.75rem 1.5rem",
            paddingCard: "1.5rem",
            paddingCompact: "0.5rem 0.75rem",
        },
        gradient: { from: "#007AFF", to: "#5AC8FA", accent: "#5AC8FA" },
        borderStyles: {
            defaultColor: "#D2D2D7",
            subtleColor: "#E8E8ED",
            strongColor: "#86868B",
            defaultWidth: "1px",
            thinWidth: "0.5px",
            thickWidth: "2px",
            defaultStyle: "solid",
        },
        stylingPreferences: {
            preferBorderless: true,
            applySpecialLayout: false,
            containerMaxWidth: "max-w-5xl",
            overviewCardBoxShadow: "0 2px 10px rgba(0,0,0,0.05)",
            headingMainText: "Think different.",
            headingSubtitleText: "Experience Innovation.",
            headingSubtitleClassName: "text-muted-foreground font-normal",
            navTitle: "Apple Design System",
        },
        supplementaryChartColors: ["#007AFF", "#5AC8FA", "#34C759", "#FF9500", "#FF3B30"],
    }

   