name: Generate Theme

on:
  # Manual trigger
  workflow_dispatch:
  
  # Trigger on Sanity webhook
  repository_dispatch:
    types: [sanity-publish-designTokens]
  
  # Optional: Also trigger on direct changes to the theme system
  push:
    branches: [main]
    paths:
      - 'sanity/desk-organized-sanity-utilities/nextgen-styleguide/**'

jobs:
  generate-theme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate theme files
        run: npm run generate-theme
        env:
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET || 'production' }}
          SANITY_API_VERSION: ${{ secrets.SANITY_API_VERSION || '2023-01-01' }}
          SANITY_READ_TOKEN: ${{ secrets.SANITY_READ_TOKEN }}
          OUTPUT_DIR: './styles'
      
      # This step packages the theme for distribution
      - name: Package theme
        run: |
          mkdir -p dist
          cp styles/globals.css dist/
          cp styles/tailwind.theme.cjs dist/
          cp sanity/desk-organized-sanity-utilities/nextgen-styleguide/scripts/package.json dist/
      
      # Publish to npm registry if running on main branch and not a manual trigger
      - name: Publish package
        if: github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch'
        run: |
          cd dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      # Commit changes back to the repository
      - name: Commit theme files
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add styles/globals.css styles/tailwind.theme.cjs
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update design tokens [skip ci]" && git push) 